name: ğŸ§ª Test Python program on Linux

on:
  push:
    branches: 
      - master
  # Manual deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ“© Checkout
      uses: actions/checkout@v3
    - name: ğŸ Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: âš™ï¸ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: ğŸ§ª Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
